const LONGNAMES = [
    "United Arab Emirates dirham",
    "Afghan afghani",
    "Albanian lek",
    "Armenian dram",
    "Netherlands Antillean guilder",
    "Angolan kwanza",
    "Argentine peso",
    "Australian dollar",
    "Aruban florin",
    "Azerbaijani manat",
    "Bosnia and Herzegovina convertible mark",
    "Barbados dollar",
    "Bangladeshi taka",
    "Bulgarian lev",
    "Bahraini dinar",
    "Burundian franc",
    "Bermudian dollar",
    "Brunei dollar",
    "Boliviano",
    "Brazilian real",
    "Bahamian dollar",
    "Bitcoin",
    "Bhutanese ngultrum",
    "Botswana pula",
    // BYN has replaced BYR, but Belarussian ruble still traded under both
    "Belarusian ruble",
    "Belarusian ruble",
    "Belize dollar",
    "Canadian dollar",
    "Congolese franc",
    "Swiss franc",
    "Unidad de Fomento (funds code)",
    "Chilean peso",
    "Renminbi (Chinese) yuan",
    "Colombian peso	",
    "Costa Rican colon",
    "Cuban convertible peso",
    "Cuban peso",
    "Cape Verde escudo",
    "Czech koruna",
    "Djiboutian franc",
    "Danish krone",
    "Dominican peso",
    "Algerian dinar",
    "Egyptian pound",
    "Eritrean nakfa",
    "Ethiopian birr",
    "Euro",
    "Fiji dollar",
    "Falkland Islands pound",
    "Pound sterling",
    "Georgian lari",
    "Guernsey pound",
    "Ghanaian cedi",
    "Gibraltar pound",
    "Gambian dalasi",
    "Guinean franc",
    "Guatemalan quetzal",
    "Guyanese dollar",
    "Hong Kong dollar",
    "Honduran lempira",
    "Croatian kuna",
    "Haitian gourde",
    "Hungarian forint",
    "Indonesian rupiah",
    "Israeli new shekel",
    "Isle of Man pound",
    "Indian rupee",
    "Iraqi dinar",
    "Iranian rial",
    "Icelandic króna",
    "Jersey pound",
    "Jamaican dollar",
    "Jordanian dinar",
    "Japanese yen",
    "Kenyan shilling",
    "Kyrgyzstani som",
    "Cambodian riel",
    "Comoro franc",
    "North Korean won",
    "South Korean won",
    "Kuwaiti dinar",
    "Cayman Islands dollar",
    "Kazakhstani tenge",
    "Lao kip",
    "Lebanese pound",
    "Sri Lankan rupee",
    "Liberian dollar",
    "Lesotho loti",
    "Lithuanian litas",
    "Latvian lats",
    "Libyan dinar",
    "Moroccan dirham",
    "Moldovan leu",
    "Malagasy ariary",
    "Macedonian denar",
    "Myanmar kyat",
    "Mongolian tögrög",
    "Macanese pataca",
    "Mauritanian ouguiya",
    "Mauritian rupee",
    "Maldivian rufiyaa",
    "Malawian kwacha",
    "Mexican peso",
    "Malaysian ringgit",
    "Mozambican metical",
    "Namibian dollar",
    "Nigerian naira",
    "Nicaraguan córdoba",
    "Norwegian krone",
    "Nepalese rupee",
    "New Zealand dollar",
    "Omani rial",
    "Panamanian balboa",
    "Peruvian sol",
    "Papua New Guinean kina",
    "Philippine piso",
    "Pakistani rupee",
    "Polish złoty",
    "Paraguayan guaraní",
    "Qatari riyal",
    "Romanian leu",
    "Serbian dinar",
    "Russian ruble",
    "Rwandan franc",
    "Saudi riyal",
    "Solomon Islands dollar",
    "Seychelles rupee",
    "Sudanese pound",
    "Swedish krona",
    "Singapore dollar",
    "Saint Helena pound",
    "Sierra Leonean leone",
    "Somali shilling",
    "Surinamese dollar",
    "São Tomé and Príncipe dobra",
    "Salvadoran colón",
    "Syrian pound",
    "Swazi lilangeni",
    "Thai baht",
    "Tajikistani somoni",
    "Turkmenistan manat",
    "Tunisian dinar",
    "Tongan paʻanga",
    "Turkish lira",
    "Trinidad and Tobago dollar",
    "New Taiwan dollar",
    "Tanzanian shilling",
    "Ukrainian hryvnia",
    "Ugandan shilling",
    "United States dollar",
    "Uruguayan peso",
    "Uzbekistan som",
    "Venezuelan bolívar",
    "Vietnamese đồng",
    "Vanuatu vatu",
    "Samoan tala",
    "CFA franc BEAC",
    "Silver (one troy ounce)",
    "Gold (one troy ounce)",
    "East Caribbean dollar",
    "Special drawing rights",
    "CFA franc BCEAO",
    "CFP franc (franc Pacifique)",
    "Yemeni rial",
    "South African rand",
    // Zambian kwacha traded under ZMK and ZMW
    "Zambian kwacha",
    "Zambian kwacha",
    "Zimbabwean dollar"
]

export default LONGNAMES;