const UNICODE = {
  AED: "United Arab Emirates dirham",
  AFN: '\u060B',
  ALL: "Albanian lek",
  AMD: '\u058F',
  ANG: "Netherlands Antillean guilder",
  AOA: "Angolan kwanza",
  ARS: '\u20B1',
  AUD: 'A\u0024',
  AWG: "Aruban florin",
  AZN: '\u20BC',
  BAM: "Bosnia and Herzegovina convertible mark",
  BBD: 'Bds\u0024',
  BDT: "Bangladeshi taka",
  BGN: "Bulgarian lev",
  BHD: "Bahraini dinar",
  BIF: "Burundian franc",
  BMD: 'BD\u0024',
  BND: 'B\u0024',
  BOB: "Boliviano",
  BRL: "Brazilian real",
  BSD: 'B\u0024',
  BTC: '\u20BF',
  BTN: "Bhutanese ngultrum",
  BWP: "Botswana pula",
  // BYN has replaced BYR, but Belarussian ruble still traded under both
  BYN: '\u20BD',
  BYR: '\u20BD',
  BZD: 'BZ\u0024',
  CAD: 'Can\u0024',
  CDF: "Congolese franc",
  CHF: "Swiss franc",
  CLF: "Unidad de Fomento (funds code)",
  CLP: '\u20B1',
  CNY: "Renminbi (Chinese) yuan",
  COP: '\u20B1',
  CRC: '\u20A2',
  CUC: '\u20B1',
  CUP: '\u20B1',
  CVE: "Cape Verde escudo",
  CZK: "Czech koruna",
  DJF: "Djiboutian franc",
  DKK: "Danish krone",
  DOP: '\u20B1',
  DZD: "Algerian dinar",
  EGP: '\u20A4',
  ERN: "Eritrean nakfa",
  ETB: "Ethiopian birr",
  EUR: '\u20AC',
  FJD: 'FJ\u0024',
  FKP: '\u20A4',
  GBP: '\u20A4',
  GEL: '\u20BE',
  GGP: '\u20A4',
  GHS: '\u20B5',
  GIP: '\u20A4',
  GMD: "Gambian dalasi",
  GNF: "Guinean franc",
  GTQ: "Guatemalan quetzal",
  GYD: 'G\u0024',
  HKD: 'HK\u0024',
  HNL: "Honduran lempira",
  HRK: "Croatian kuna",
  HTG: "Haitian gourde",
  HUF: "Hungarian forint",
  IDR: "Indonesian rupiah",
  ILS: '\u20AA',
  IMP: '\u20A4',
  INR: '\u20B9',
  IQD: "Iraqi dinar",
  IRR: "Iranian rial",
  ISK: "Icelandic króna",
  JEP: '\u20A4',
  JMD: 'J\u0024',
  JOD: "Jordanian dinar",
  JPY: '\u00a5',
  KES: "Kenyan shilling",
  KGS: "Kyrgyzstani som",
  KHR: '\u17DB',
  KMF: "Comoro franc",
  KPW: '\u20A9',
  KRW: '\u20A9',
  KWD: "Kuwaiti dinar",
  KYD: 'CI\u0024',
  KZT: '\u20B8',
  LAK: '\u20AD',
  LBP: '\u20A4',
  LKR: '\u20A8',
  LRD: 'L\u0024',
  LSL: "Lesotho loti",
  LTL: "Lithuanian litas",
  LVL: "Latvian lats",
  LYD: "Libyan dinar",
  MAD: "Moroccan dirham",
  MDL: "Moldovan leu",
  MGA: "Malagasy ariary",
  MKD: "Macedonian denar",
  MMK: "Myanmar kyat",
  MNT: '\u20AE',
  MOP: "Macanese pataca",
  MRO: "Mauritanian ouguiya",
  MUR: '\u20A8',
  MVR: "Maldivian rufiyaa",
  MWK: "Malawian kwacha",
  MXN: '\u20B1',
  MYR: "Malaysian ringgit",
  MZN: "Mozambican metical",
  NAD: 'N\u0024',
  NGN: '\u20A6',
  NIO: "Nicaraguan córdoba",
  NOK: "Norwegian krone",
  NPR: '\u20A8',
  NZD: 'NZ\u0024',
  OMR: "Omani rial",
  PAB: "Panamanian balboa",
  PEN: "Peruvian sol",
  PGK: "Papua New Guinean kina",
  PHP: '\u20B1',
  PKR: '\u20A8',
  PLN: "Polish złoty",
  PYG: '\u20B2',
  QAR: "Qatari riyal",
  RON: "Romanian leu",
  RSD: "Serbian dinar",
  RUB: '\u20BD',
  RWF: "Rwandan franc",
  SAR: "Saudi riyal",
  SBD: 'SI\u0024',
  SCR: '\u20A8',
  SDG: '\u20A4',
  SEK: "Swedish krona",
  SGD: 'S\u0024',
  SHP: '\u20A4',
  SLL: "Sierra Leonean leone",
  SOS: "Somali shilling",
  SRD: 'Sr\u0024',
  STD: "São Tomé and Príncipe dobra",
  SVC: '\u20A2',
  SYP: '\u20A4',
  SZL: "Swazi lilangeni",
  THB: '\u0E3F',
  TJS: "Tajikistani somoni",
  TMT: '\u20BC',
  TND: "Tunisian dinar",
  TOP: "Tongan paʻanga",
  TRY: '\u20BA',
  TTD: 'TT\u0024',
  TWD: 'NT\u0024',
  TZS: "Tanzanian shilling",
  UAH: '\u20B4',
  UGX: "Ugandan shilling",
  USD: 'US\u0024',
  UYU: '\u20B1',
  UZS: "Uzbekistan som",
  VEF: "Venezuelan bolívar",
  VND: '\u20AB',
  VUV: "Vanuatu vatu",
  WST: "Samoan tala",
  XAF: "CFA franc BEAC",
  XAG: "Silver (one troy ounce)",
  XAU: "Gold (one troy ounce)",
  XCD: 'EC\u0024',
  XDR: "Special drawing rights",
  XOF: "CFA franc BCEAO",
  XPF: "CFP franc (franc Pacifique)",
  YER: "Yemeni rial",
  ZAR: "South African rand",
  // Zambian kwacha traded under ZMK and ZMW
  ZMK: "Zambian kwacha",
  ZMW: "Zambian kwacha",
  ZWL: 'Z\u0024'
}

export default UNICODE;