const UNICODE = {
  AED: null, //"United Arab Emirates dirham",
  AFN: '\u060B',
  ALL: null, //"Albanian lek",
  AMD: '\u058F',
  ANG: null, //"Netherlands Antillean guilder",
  AOA: null, //"Angolan kwanza",
  ARS: '\u20B1',
  AUD: 'A\u0024',
  AWG: null, //"Aruban florin",
  AZN: '\u20BC',
  BAM: null, //"Bosnia and Herzegovina convertible mark",
  BBD: 'Bds\u0024',
  BDT: null, //"Bangladeshi taka",
  BGN: null, //"Bulgarian lev",
  BHD: null, //"Bahraini dinar",
  BIF: null, //"Burundian franc",
  BMD: 'BD\u0024',
  BND: 'B\u0024',
  BOB: null, //"Boliviano",
  BRL: null, //"Brazilian real",
  BSD: 'B\u0024',
  BTC: '\u20BF',
  BTN: null, //"Bhutanese ngultrum",
  BWP: null, //"Botswana pula",
  // BYN has replaced BYR, but Belarussian ruble still traded under both
  BYN: '\u20BD',
  BYR: '\u20BD',
  BZD: 'BZ\u0024',
  CAD: 'Can\u0024',
  CDF: null, //"Congolese franc",
  CHF: null, //"Swiss franc",
  CLF: null, //"Unidad de Fomento (funds code)",
  CLP: '\u20B1',
  CNY: null, //"Renminbi (Chinese) yuan",
  COP: '\u20B1',
  CRC: '\u20A2',
  CUC: '\u20B1',
  CUP: '\u20B1',
  CVE: null, //"Cape Verde escudo",
  CZK: null, //"Czech koruna",
  DJF: null, //"Djiboutian franc",
  DKK: null, //"Danish krone",
  DOP: '\u20B1',
  DZD: null, //"Algerian dinar",
  EGP: '\u20A4',
  ERN: null, //"Eritrean nakfa",
  ETB: null, //"Ethiopian birr",
  EUR: '\u20AC',
  FJD: 'FJ\u0024',
  FKP: '\u20A4',
  GBP: '\u20A4',
  GEL: '\u20BE',
  GGP: '\u20A4',
  GHS: '\u20B5',
  GIP: '\u20A4',
  GMD: null, //"Gambian dalasi",
  GNF: null, //"Guinean franc",
  GTQ: null, //"Guatemalan quetzal",
  GYD: 'G\u0024',
  HKD: 'HK\u0024',
  HNL: null, //"Honduran lempira",
  HRK: null, //"Croatian kuna",
  HTG: null, //"Haitian gourde",
  HUF: null, //"Hungarian forint",
  IDR: null, //"Indonesian rupiah",
  ILS: '\u20AA',
  IMP: '\u20A4',
  INR: '\u20B9',
  IQD: null, //"Iraqi dinar",
  IRR: null, //"Iranian rial",
  ISK: null, //"Icelandic króna",
  JEP: '\u20A4',
  JMD: 'J\u0024',
  JOD: null, //"Jordanian dinar",
  JPY: '\u00a5',
  KES: null, //"Kenyan shilling",
  KGS: null, //"Kyrgyzstani som",
  KHR: '\u17DB',
  KMF: null, //"Comoro franc",
  KPW: '\u20A9',
  KRW: '\u20A9',
  KWD: null, //"Kuwaiti dinar",
  KYD: 'CI\u0024',
  KZT: '\u20B8',
  LAK: '\u20AD',
  LBP: '\u20A4',
  LKR: '\u20A8',
  LRD: 'L\u0024',
  LSL: null, //"Lesotho loti",
  LTL: null, //"Lithuanian litas",
  LVL: null, //"Latvian lats",
  LYD: null, //"Libyan dinar",
  MAD: null, //"Moroccan dirham",
  MDL: null, //"Moldovan leu",
  MGA: null, //"Malagasy ariary",
  MKD: null, //"Macedonian denar",
  MMK: null, //"Myanmar kyat",
  MNT: '\u20AE',
  MOP: null, //"Macanese pataca",
  MRO: null, //"Mauritanian ouguiya",
  MUR: '\u20A8',
  MVR: null, //"Maldivian rufiyaa",
  MWK: null, //"Malawian kwacha",
  MXN: '\u20B1',
  MYR: null, //"Malaysian ringgit",
  MZN: null, //"Mozambican metical",
  NAD: 'N\u0024',
  NGN: '\u20A6',
  NIO: null, //"Nicaraguan córdoba",
  NOK: null, //"Norwegian krone",
  NPR: '\u20A8',
  NZD: 'NZ\u0024',
  OMR: null, //"Omani rial",
  PAB: null, //"Panamanian balboa",
  PEN: null, //"Peruvian sol",
  PGK: null, //"Papua New Guinean kina",
  PHP: '\u20B1',
  PKR: '\u20A8',
  PLN: null, //"Polish złoty",
  PYG: '\u20B2',
  QAR: null, //"Qatari riyal",
  RON: null, //"Romanian leu",
  RSD: null, //"Serbian dinar",
  RUB: '\u20BD',
  RWF: null, //"Rwandan franc",
  SAR: null, //"Saudi riyal",
  SBD: 'SI\u0024',
  SCR: '\u20A8',
  SDG: '\u20A4',
  SEK: null, //"Swedish krona",
  SGD: 'S\u0024',
  SHP: '\u20A4',
  SLL: null, //"Sierra Leonean leone",
  SOS: null, //"Somali shilling",
  SRD: 'Sr\u0024',
  STD: null, //"São Tomé and Príncipe dobra",
  SVC: '\u20A2',
  SYP: '\u20A4',
  SZL: null, //"Swazi lilangeni",
  THB: '\u0E3F',
  TJS: null, //"Tajikistani somoni",
  TMT: '\u20BC',
  TND: null, //"Tunisian dinar",
  TOP: null, //"Tongan paʻanga",
  TRY: '\u20BA',
  TTD: 'TT\u0024',
  TWD: 'NT\u0024',
  TZS: null, //"Tanzanian shilling",
  UAH: '\u20B4',
  UGX: null, //"Ugandan shilling",
  USD: 'US\u0024',
  UYU: '\u20B1',
  UZS: null, //"Uzbekistan som",
  VEF: null, //"Venezuelan bolívar",
  VND: '\u20AB',
  VUV: null, //"Vanuatu vatu",
  WST: null, //"Samoan tala",
  XAF: null, //"CFA franc BEAC",
  XAG: null, //"Silver (one troy ounce)",
  XAU: null, //"Gold (one troy ounce)",
  XCD: 'EC\u0024',
  XDR: null, //"Special drawing rights",
  XOF: null, //"CFA franc BCEAO",
  XPF: null, //"CFP franc (franc Pacifique)",
  YER: null, //"Yemeni rial",
  ZAR: null, //"South African rand",
  // Zambian kwacha traded under ZMK and ZMW
  ZMK: null, //"Zambian kwacha",
  ZMW: null, //"Zambian kwacha",
  ZWL: 'Z\u0024'
}

export default UNICODE;